import React, {useEffect, useMemo, useState} from "react";
import {MapContainer, TileLayer, Marker, Popup, Polyline, Circle} from "react-leaflet";
import L from "leaflet";
import "leaflet/dist/leaflet.css";

const DEMO_AMBULANCE=[23.3441,85.3096];
const DEMO_HOSPITAL=[23.3615,85.3250];
// Demo police location. In the real system this would come from an authorized police GPS/device.
const DEMO_POLICE=[23.3500,85.3150];
const POLICE_ALERT_RADIUS_KM=1;

const ambulanceIcon=L.divIcon({className:"custom-marker",html:`<div style="width:24px;height:24px;background:#4285F4;border:4px solid white;border-radius:50%;box-shadow:0 2px 8px rgba(0,0,0,.35)"></div>`,iconSize:[32,32],iconAnchor:[16,16]});
const hospitalIcon=L.divIcon({className:"custom-marker",html:`<div style="width:28px;height:28px;background:#EA4335;border:3px solid white;border-radius:50% 50% 50% 0;transform:rotate(-45deg);box-shadow:0 2px 8px rgba(0,0,0,.35)"><div style="width:10px;height:10px;background:white;border-radius:50%;position:absolute;top:6px;left:6px"></div></div>`,iconSize:[34,34],iconAnchor:[17,34],popupAnchor:[0,-30]});
const policeIcon=L.divIcon({className:"custom-marker",html:`<div style="width:30px;height:30px;background:#1f2937;border:3px solid white;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-size:16px;box-shadow:0 2px 8px rgba(0,0,0,.35)">🚔</div>`,iconSize:[36,36],iconAnchor:[18,18]});

function distanceKm(a,b){const R=6371,rad=Math.PI/180;const dLat=(b[0]-a[0])*rad,dLng=(b[1]-a[1])*rad;const x=Math.sin(dLat/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}

export default function LiveMap(){
 const [gpsLocation,setGpsLocation]=useState(null),[gpsError,setGpsError]=useState(""),[route,setRoute]=useState([]),[distance,setDistance]=useState(null),[duration,setDuration]=useState(null),[usingDemo,setUsingDemo]=useState(false),[lastUpdated,setLastUpdated]=useState(null),[routeStatus,setRouteStatus]=useState("Calculating route...");
 const ambulanceLocation=gpsLocation||DEMO_AMBULANCE;
 const policeDistance=useMemo(()=>distanceKm(ambulanceLocation,DEMO_POLICE),[ambulanceLocation]);
 const policeInRange=policeDistance<=POLICE_ALERT_RADIUS_KM;
 const patientEmergencyCategory="Critical / High Priority";

 useEffect(()=>{if(!navigator.geolocation){setGpsError("This browser/device does not support Geolocation.");setUsingDemo(true);return}const id=navigator.geolocation.watchPosition(p=>{setGpsLocation([p.coords.latitude,p.coords.longitude]);setGpsError("");setUsingDemo(false);setLastUpdated(new Date())},e=>{console.warn(e.message);setGpsError("GPS permission allow nahi hui. Demo location use ho rahi hai.");setUsingDemo(true)},{enableHighAccuracy:true,maximumAge:2000,timeout:10000});return()=>navigator.geolocation.clearWatch(id)},[]);
 useEffect(()=>{const controller=new AbortController();async function getRoute(){try{setRouteStatus("Recalculating route...");const [fromLat,fromLng]=ambulanceLocation,[toLat,toLng]=DEMO_HOSPITAL;const url=`https://router.project-osrm.org/route/v1/driving/${fromLng},${fromLat};${toLng},${toLat}?overview=full&geometries=geojson`;const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error(`Routing request failed: ${r.status}`);const d=await r.json();if(d.routes?.length){const x=d.routes[0];setRoute(x.geometry.coordinates.map(([lng,lat])=>[lat,lng]));setDistance((x.distance/1000).toFixed(2));setDuration(Math.round(x.duration/60));setRouteStatus("Live route updated")}else{setRouteStatus("Route unavailable")}}catch(e){if(e.name!=="AbortError")console.error(e)}}getRoute();return()=>controller.abort()},[gpsLocation,usingDemo]);
 return <section className="map-card"><div className="map"><MapContainer center={ambulanceLocation} zoom={14} style={{height:"100%",width:"100%"}} dragging touchZoom scrollWheelZoom doubleClickZoom zoomControl keyboard><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Marker position={ambulanceLocation} icon={ambulanceIcon}><Popup>🚑 <b>Ambulance AMB102</b><br/>{gpsLocation?"LIVE GPS Location":"Demo Location"}</Popup></Marker><Marker position={DEMO_HOSPITAL} icon={hospitalIcon}><Popup>🏥 <b>City Hospital</b><br/>Emergency Department</Popup></Marker><Marker position={DEMO_POLICE} icon={policeIcon}><Popup>🚔 <b>Authorized Police Unit</b><br/>Traffic assistance unit</Popup></Marker><Circle center={ambulanceLocation} radius={1000} pathOptions={{weight:1,dashArray:"6 6"}}/>{route.length>0&&<Polyline positions={route} pathOptions={{weight:5}}/>}</MapContainer></div><div className="info"><div className="status">{gpsLocation?<>📍 <b>GPS Active</b> — {gpsLocation[0].toFixed(5)}, {gpsLocation[1].toFixed(5)}{lastUpdated&&<> &nbsp;•&nbsp; Updated {lastUpdated.toLocaleTimeString()}</>}</>:<>📍 <b>Demo GPS</b> — Allow location permission to use live GPS.</>}</div>{gpsError&&<div className="status">⚠️ {gpsError}</div>}{policeInRange?<div className="alert"><h3>🔔 Police Alert Triggered</h3><div>🚑 Ambulance <b>AMB102</b> is within <b>1 km</b> of an authorized police unit.</div><div>📍 Ambulance location: {ambulanceLocation[0].toFixed(5)}, {ambulanceLocation[1].toFixed(5)}</div><div>🏥 Destination: <b>City Hospital</b></div><div>⚠️ Patient emergency category: <b>{patientEmergencyCategory}</b></div><div>🚦 Action: Police can coordinate traffic clearance to give the ambulance a safe passage.</div></div>:<div className="police"><h3>🚔 Police Proximity</h3><div>Nearest authorized police unit: <b>{policeDistance.toFixed(2)} km</b> away <span className="badge">No alert yet</span></div></div>}<div className="status">🛣️ <b>Route:</b> {routeStatus}</div><div className="stats"><div className="stat"><span>📏 Distance</span><strong>{distance?`${distance} km`:"Calculating..."}</strong></div><div className="stat"><span>⏱️ ETA</span><strong>{duration!=null?`${duration} min`:"Calculating..."}</strong></div><div className="stat"><span>🚑 Ambulance</span><strong>AMB102</strong></div><div className="stat"><span>🏥 Destination</span><strong>City Hospital</strong></div></div><div className="police"><h3>🚔 Police Alert Logic</h3><div><b>Range:</b> 1 km &nbsp; | &nbsp; <b>Patient category:</b> {patientEmergencyCategory} &nbsp; | &nbsp; <b>Status:</b> {policeInRange?"Alert sent (demo)":"Waiting"}</div></div></div></section>
}
